### ISSUE TITLE
Anything on the idea of B-Splines

### ISSUE THREAD

**Issue by lonnietc** [ricardosantos79/pinescript#2]
Hello,

I am trying to learn Pine Script for Tradingview and am looking at an indicator "BSM" that gives Bollinger Bands and a signal curve. I would like to see if I could generate a "smooth" curve fitting the signal to be able to see when the smooth curve valleys and peaks.  I will then try to get the slope as new data comes and when it reaches approximate zero then I will send some trigger.

Do you have any ideas on who to maybe go about doing a B-Spline or Polynomial Regression that will interpolate through the curve?

Best Regards
Lonnie

**Comment by ricardosantos79** [comment]
awnsered on TV.
